spring:
  profiles:
    active: dev
    group:
      dev: client,oauth,jwt,gcp,payment
      prod: client,oauth,jwt,aws,gcp,payment

  messages:
    basename: errors

  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true