spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root

  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
  h2:
    console:
      enabled: true
  profiles:
    include: oauth,jwt,aws