= AImage API Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:
:docinfo: shared-head

= Overview

== 공통 에러 응답

----
HTTP/1.1 400 Bad Request
Content-Type: text/plain;charset=UTF-8
Content-Length:

{
    "errors": [
        {
            "field": "...",
            "message": "..."
        }
    ]
}
----

== Category APIs

=== 새 카테고리 생성
operation::category-api-controller-test/save[snippets='request-fields,http-request,response-fields,http-response']

=== 전체 카테고리 조회
operation::category-api-controller-test/find-all[snippets='http-request,response-fields,http-response']

=== 카테고리 수정
operation::category-api-controller-test/update[snippets='request-fields,http-request,response-fields,http-response']

=== 카테고리 삭제
operation::category-api-controller-test/delete-one[snippets='http-request,http-response']


== Brand APIs

=== 새 브랜드 생성
operation::brand-api-controller-test/save[snippets='request-fields,http-request,response-fields,http-response']

=== 전체 브랜드 조회
operation::brand-api-controller-test/find-all[snippets='http-request,response-fields,http-response']

=== 카테고리 id 별 전체 브랜드 조회
operation::brand-api-controller-test/find-all-by-category-id[snippets='http-request,response-fields,http-response']

=== 브랜드 수정
operation::brand-api-controller-test/update[snippets='request-fields,http-request,response-fields,http-response']

=== 브랜드 삭제
operation::brand-api-controller-test/delete-one[snippets='http-request,http-response']


== Voucher APIs

=== 새 기프티콘 생성
operation::voucher-api-controller-test/save[snippets='request-fields,http-request,response-fields,http-response']

=== 기프티콘 단일 조회
operation::voucher-api-controller-test/find-one[snippets='http-request,response-fields,http-response']

=== 기프티콘 전체 조회
operation::voucher-api-controller-test/find-all[snippets='http-request,response-fields,http-response']

=== 브랜드 이름 별 기프티콘 조회
operation::voucher-api-controller-test/find-all-by-brand-name[snippets='http-request,response-fields,http-response']

=== 기프티콘 id 별 판매중인 기프티콘 조회
operation::voucher-api-controller-test/find-selling-list-by-voucher-id[snippets='http-request,response-fields,http-response']

=== 기프티콘 수정
operation::voucher-api-controller-test/update[snippets='request-fields,http-request,response-fields,http-response']

=== 기프티콘 삭제
operation::voucher-api-controller-test/delete-one[snippets='http-request,http-response']


== VoucherForSale APIs

=== 기프티콘 판매 등록
operation::voucher-for-sale-api-controller-test/save[snippets='request-fields,http-request,response-fields,http-response']

=== 판매중인 기프티콘 삭제
operation::voucher-for-sale-api-controller-test/delete-one[snippets='http-request,http-response']


== PurchasedVoucher APIs

=== 기프티콘 구매 등록
operation::purchased-voucher-api-controller-test/save-all[snippets='request-fields,http-request,response-fields,http-response']

=== 구매한 기프티콘 단일 조회
operation::purchased-voucher-api-controller-test/find-one[snippets='http-request,response-fields,http-response']

=== 사용자 이름 별 구매한 기프티콘 전체 조회
operation::purchased-voucher-api-controller-test/find-all-by-username[snippets='http-request,response-fields,http-response']

=== 구매한 기프티콘 사용 유효 여부 수정
operation::purchased-voucher-api-controller-test/update-validity[snippets='http-request,response-fields,http-response']


== LikedVoucher APIs

=== 기프티콘 찜하기 등록
operation::liked-voucher-api-controller-test/save[snippets='http-request,response-fields,http-response']

=== 사용자 이름 별 찜한 기프티콘 전체 조회
operation::liked-voucher-api-controller-test/find-all-by-username[snippets='http-request,response-fields,http-response']

=== 기프티콘 찜하기 취소
operation::liked-voucher-api-controller-test/delete-one[snippets='http-request,http-response']