= AImage API Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:
:docinfo: shared-head


== 공통 에러 응답
----
HTTP/1.1 404 Not Found
Content-Type: application/json

{
    "error": {
        "status": "..."
        "code": "...",
        "message": "..."
    }
}
----


:sectnums:
== Member APIs
:sectnums!:

=== 회원 계정 삭제
operation::member-api-controller-test/delete-one[snippets='path-parameters,http-request,http-response']


:sectnums:
== Category APIs
:sectnums!:

=== 새 카테고리 생성
operation::category-api-controller-test/save[snippets='request-fields,http-request,response-fields,http-response']

=== 전체 카테고리 조회
operation::category-api-controller-test/find-all[snippets='http-request,response-fields,http-response']

=== 카테고리 수정
operation::category-api-controller-test/update[snippets='path-parameters,request-fields,http-request,response-fields,http-response']

=== 카테고리 삭제
operation::category-api-controller-test/delete-one[snippets='path-parameters,http-request,http-response']


:sectnums:
== Brand APIs
:sectnums!:

=== 새 브랜드 생성
operation::brand-api-controller-test/save[snippets='request-fields,http-request,response-fields,http-response']

=== 전체 브랜드 조회
operation::brand-api-controller-test/find-all[snippets='http-request,response-fields,http-response']

=== 카테고리 id 별 전체 브랜드 조회
operation::brand-api-controller-test/find-all-by-category-id[snippets='query-parameters,http-request,response-fields,http-response']

=== 브랜드 수정
operation::brand-api-controller-test/update[snippets='path-parameters,request-fields,http-request,response-fields,http-response']

=== 브랜드 삭제
operation::brand-api-controller-test/delete-one[snippets='path-parameters,http-request,http-response']


:sectnums:
== Voucher APIs
:sectnums!:

=== 새 기프티콘 생성
operation::voucher-api-controller-test/save[snippets='request-fields,http-request,response-fields,http-response']

=== 기프티콘 단일 조회
operation::voucher-api-controller-test/find-one[snippets='path-parameters,http-request,response-fields,http-response']

=== 기프티콘 전체 조회
operation::voucher-api-controller-test/find-all[snippets='http-request,response-fields,http-response']

=== 브랜드 이름 별 기프티콘 조회
operation::voucher-api-controller-test/find-all-by-brand-name[snippets='query-parameters,http-request,response-fields,http-response']

=== 기프티콘 id 별 판매중인 기프티콘 조회
operation::voucher-api-controller-test/find-selling-list-by-voucher-id[snippets='path-parameters,http-request,response-fields,http-response']

=== 기프티콘 수정
operation::voucher-api-controller-test/update[snippets='path-parameters,request-fields,http-request,response-fields,http-response']

=== 기프티콘 삭제
operation::voucher-api-controller-test/delete-one[snippets='path-parameters,http-request,http-response']


:sectnums:
== VoucherForSale APIs
:sectnums!:

=== 기프티콘 판매 등록
operation::voucher-for-sale-api-controller-test/save[snippets='request-fields,http-request,response-fields,http-response']

=== 판매중인 기프티콘 삭제
operation::voucher-for-sale-api-controller-test/delete-one[snippets='path-parameters,http-request,http-response']


:sectnums:
== PurchasedVoucher APIs
:sectnums!:

=== 기프티콘 구매 등록
operation::purchased-voucher-api-controller-test/save-all[snippets='request-fields,http-request,response-fields,http-response']

=== 구매한 기프티콘 단일 조회
operation::purchased-voucher-api-controller-test/find-one[snippets='path-parameters,http-request,response-fields,http-response']

=== 회원 별 구매한 기프티콘 전체 조회
operation::purchased-voucher-api-controller-test/find-all-by-username[snippets='http-request,response-fields,http-response']

=== 구매한 기프티콘 사용 유효 여부 수정
operation::purchased-voucher-api-controller-test/update-validity[snippets='path-parameters,http-request,response-fields,http-response']


:sectnums:
== LikedVoucher APIs
:sectnums!:

=== 기프티콘 찜하기 등록
operation::liked-voucher-api-controller-test/save[snippets='http-request,response-fields,http-response']

=== 회원 별 찜한 기프티콘 전체 조회
operation::liked-voucher-api-controller-test/find-all-by-username[snippets='http-request,response-fields,http-response']

=== 기프티콘 찜하기 취소
operation::liked-voucher-api-controller-test/delete-one[snippets='path-parameters,http-request,http-response']