= 기브미콘 API Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:docinfo: shared-head

== 공통 에러 응답
----
HTTP/1.1 404 Not Found
Content-Type: application/json

{
    "error": {
        "status": "..."
        "code": "...",
        "message": "..."
    }
}
----
{sp} +


:sectnums:
== Member APIs
{sp} +

=== 회원 계정 삭제
operation::member-controller-test/delete-one[snippets='path-parameters,http-request,http-response']
:sectnums!:
{sp} +

:sectnums:
== Token Issue/Reissue APIs
{sp} +

=== Access Token & Refresh Token 발급 요청
operation::token-issue-api-controller-test/issue-token[snippets='query-parameters,http-request,response-fields,http-response']
{sp} +

=== Refresh Token 재발급 요청
operation::token-issue-api-controller-test/reissue-token[snippets='http-request,response-fields,http-response']
:sectnums!:
{sp} +


:sectnums:
== Category APIs
{sp} +

=== 전체 카테고리 조회
operation::category-controller-test/find-all[snippets='http-request,response-fields,http-response']
{sp} +

:sectnums:
== Brand APIs
{sp} +

=== 카테고리 id 별 전체 브랜드 조회
operation::brand-controller-test/find-all-by-category-id[snippets='query-parameters,http-request,response-fields,http-response']
{sp} +

:sectnums:
== Voucher-Kind APIs
{sp} +

=== 기프티콘 종류 단일 조회
operation::voucher-kind-controller-test/find-one[snippets='path-parameters,http-request,response-fields,http-response']
{sp} +

=== 기프티콘 종류 전체 조회
operation::voucher-kind-controller-test/find-all[snippets='http-request,response-fields,http-response']
{sp} +

=== 브랜드 id 별 기프티콘 종류 조회
operation::voucher-kind-controller-test/find-all-by-brand-id[snippets='query-parameters,http-request,response-fields,http-response']
{sp} +


:sectnums:
== Voucher APIs
{sp} +

=== 기프티콘 판매 등록
operation::voucher-controller-test/save[snippets='request-parts,http-request,response-fields,http-response']
{sp} +

=== 판매자별 기프티콘 조회
operation::voucher-controller-test/find-all-by-seller[snippets='http-request,response-fields,http-response']
{sp} +

=== 상태와 판매자별 기프티콘 조회
operation::voucher-controller-test/find-all-by-status-and-username[snippets='query-parameters,http-request,response-fields,http-response']
{sp} +

=== voucher-kind id별 현재 판매 중인 기프티콘 조회
operation::voucher-controller-test/find-all-for-sale-by-voucher-kind-id[snippets='query-parameters,http-request,response-fields,http-response']
{sp} +

=== 기프티콘 이미지 조회
operation::voucher-controller-test/find-image-url[snippets='path-parameters,http-request,response-fields,http-response']
{sp} +


:sectnums:
== PurchasedVoucher APIs
{sp} +

=== 기프티콘 구매 등록 (1개 이상)
operation::purchased-voucher-controller-test/save-all[snippets='request-fields,http-request,response-fields,http-response']
{sp} +

=== 구매한 기프티콘 단일 조회
operation::purchased-voucher-controller-test/find-one[snippets='path-parameters,http-request,response-fields,http-response']
{sp} +

=== 회원 별 구매한 기프티콘 전체 조회
operation::purchased-voucher-controller-test/find-all-by-username[snippets='http-request,response-fields,http-response']
{sp} +

=== 구매한 기프티콘 사용 처리
operation::purchased-voucher-controller-test/set-used[snippets='path-parameters,http-request,response-fields,http-response']
:sectnums!:
{sp} +


:sectnums:
== LikedVoucher APIs
{sp} +

=== 기프티콘 찜하기 등록
operation::liked-voucher-controller-test/save[snippets='http-request,response-fields,http-response']
{sp} +

=== 회원 별 찜한 기프티콘 전체 조회
operation::liked-voucher-controller-test/find-all-by-username[snippets='http-request,response-fields,http-response']
{sp} +

=== 기프티콘 찜하기 취소
operation::liked-voucher-controller-test/delete-one[snippets='path-parameters,http-request,http-response']
:sectnums!:
{sp} +


:sectnums:
== Order APIs
{sp} +

=== 주문 요청 처리
operation::order-controller-test/place-order[snippets='request-fields,http-request,response-fields,http-response']
{sp} +

=== 주문 조회
operation::order-controller-test/find-order[snippets='path-parameters,http-request,response-fields,http-response']
{sp} +

=== 주문 취소
operation::order-controller-test/cancel-order[snippets='path-parameters,http-request,http-response']
:sectnums!:
{sp} +


:sectnums:
== Payment APIs
{sp} +

=== 결제 확인 요청
operation::payment-controller-test/confirm-payment[snippets='request-fields,http-request,response-fields,http-response']
{sp} +

=== 결제 내역 조회
operation::payment-controller-test/find-payment-history[snippets='path-parameters,http-request,response-fields,http-response']
{sp} +