= 기브미콘 API Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:docinfo: shared-head

== 공통 에러 응답
----
HTTP/1.1 404 Not Found
Content-Type: application/json

{
    "error": {
        "status": "..."
        "code": "...",
        "message": "..."
    }
}
----
{sp} +

== Voucher 상태 코드
|===
|Status Code|Status|Description

|`+0+`
|`+SALE_REQUESTED+`
|판매 요청 중인 상태

|`+1+`
|`+SALE_REJECTED+`
|판매 요청이 거절된 상태

|`+2+`
|`+FOR_SALE+`
|현재 판매 중인 상태

|`+3+`
|`+ORDER_PLACED+`
|주문 체결된 상태

|`+4+`
|`+SOLD+`
|판매 완료된 상태

|`+5+`
|`+EXPIRED+`
|유효기간이 만료된 상태
|===
{sp} +

:sectnums:
== Voucher APIs
{sp} +

=== 기프티콘 판매 등록
operation::voucher-controller-test/save[snippets='request-parts,http-request,response-fields,http-response']
{sp} +

=== 판매자별 기프티콘 조회
operation::voucher-controller-test/find-all-by-seller[snippets='http-request,response-fields,http-response']
{sp} +

=== 상태와 판매자별 기프티콘 조회
operation::voucher-controller-test/find-all-by-status-and-username[snippets='query-parameters,http-request,response-fields,http-response']
{sp} +

=== voucher-kind id별 현재 판매 중인 기프티콘 조회
operation::voucher-controller-test/find-all-for-sale-by-voucher-kind-id[snippets='query-parameters,http-request,response-fields,http-response']
{sp} +

=== 기프티콘 이미지 조회
operation::voucher-controller-test/find-image-url[snippets='path-parameters,http-request,response-fields,http-response']
:sectnums!:
{sp} +